FROM debian:stretch-slim

ENV CHPROXY_VERSION 1.12.0

RUN set -ex \
  && apt update \
  && apt install ca-certificates openssl tar gzip wget --no-install-recommends -y \
  && rm -rf /var/lib/apt/lists/*


# 
        
RUN wget https://github.com/Vertamedia/chproxy/releases/download/${CHPROXY_VERSION}/chproxy-linux-amd64-${CHPROXY_VERSION}.tar.gz  \
  && tar xzvf chproxy-linux-amd64-${CHPROXY_VERSION}.tar.gz \
  && mv chproxy-linux-amd64 /bin/chproxy

COPY config.yml /config.yml

EXPOSE 9090

CMD ["/bin/chproxy", "-config=/config.yml"]
